---
title: "Simplifying Maxent model-fitting in R"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
```

_This package is a work in progress_

## Installation

```{r, eval=FALSE}
remotes::install_github('johnbaums/sdm')
remotes::install_github('johnbaums/rmaxent')
```


## Example

The below example is purely for demonstration. I have not assessed the quality 
of occurrence data or of the resulting model.

```{r}
library(rmaxent)
library(sdm)
library(raster)
library(sf)

# If Maxent is < 3.4.0, download Maxent 3.4.1 and copy to the dismo/java folder
if(maxent_version() < '3.4.0') rmaxent::get_maxent('3.4.1')
```


### Get and clean occurrence data

```{r}
occ <- get_ala_occ('Cercartetus nanus', target_crs=3577)
occ_clean <- clean_occ(occ)
```


### Load predictors

```{r}
# Load some enviro rasters
bio <- raster::getData('worldclim', var='bio', res=10)
e <- raster::extent(112, 154, -44, -9)
bio_moll <- raster::projectRaster(
  raster::crop(
    raster::stack(list.files('wc10', '\\.bil$', full=TRUE)), 
    e, snap='out'),
  crs=raster::crs(occ_clean),
  res=15000
)
```


### Generate background data

10,000 random points within 500km of occurrences

```{r}
bg <- sample_background(n=10000, occ=occ_clean, template_raster=bio_moll, 
                        buffer_width=300000)
```

```{r}
plot(bio_moll$bio1)
points(sf::as_Spatial(bg), pch='.')
points(sf::as_Spatial(occ_clean), pch=20, cex=0.5, col='red')
```


### Fit model

```{r}
m <- fit_maxent(occurrence=occ_clean, background=bg, 
                predictors=bio_moll[[c(1, 5, 6, 12)]], 
                outdir=tempdir(), features='lpq', beta=2, 
                replicates=5, curves=TRUE, 
                full_args=c(writebackgroundpredictions=TRUE),
                outputformat='raw',
                return_model=TRUE)
```


### Project model

```{r}
pred <- rmaxent::project(m$model_full, bio_moll)
plot(pred$prediction_logistic)
plot(pred$prediction_cloglog)
```

